import { SocketProvider } from '@/Context/SocketProvider';
import TanstackProvider from '@/Context/TanstackProvider';
import ToasterContext from '@/Context/ToasterContext';
import type { Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';
import './globals.css';

export const metadata: Metadata = {
    title: 'Music Room',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <NextTopLoader />

                <SocketProvider>
                    <TanstackProvider>
                        <ToasterContext />
                        {children}
                    </TanstackProvider>
                </SocketProvider>
            </body>
        </html>
    );
}
